"""Alembic-Kette gegen eine echte Datenbank mit Bestandsdaten in allen Tabellen (Issue #390).

Vorher wurden Migrationen nur gemockt getestet; zwei echte Fehler (SQLite-Batch-Mode,
PostgreSQL-Enum-Werte) blieben unentdeckt. Standard ist SQLite; mit
``MIGRATION_TEST_DATABASE_URL`` laufen dieselben Tests gegen PostgreSQL (CI-Job).
"""

from alembic import command
from alembic.config import Config as AlembicConfig
from alembic.util.exc import AutogenerateDiffsDetected
from app.models import Category
from app.models import CategoryShelfLife
from app.models import Item
from app.models import ItemType
from app.models import Location
from app.models import LocationType
from app.models import LoginAttempt
from app.models import StorageType
from app.models import SystemSettings
from app.models import User
from app.models import Withdrawal
from datetime import date
from datetime import datetime
from pathlib import Path
import pytest
import sqlalchemy as sa
from sqlmodel import Session
from sqlmodel import select


INITIAL_REVISION = "d34a94a28640"
VERSIONS_DIR = Path(__file__).resolve().parents[2] / "app" / "alembic" / "versions"
NOW = datetime(2026, 1, 1, 12, 0, 0)

# Leichtgewichtige Tabellen im Stand des Initialschemas (dialektneutral; Enum-Spalten typisiert,
# sonst schickt psycopg VARCHAR und PostgreSQL lehnt ab)
storage_type_enum = sa.Enum("FROZEN", "CHILLED", "AMBIENT", name="storagetype")
location_type_enum = sa.Enum("FROZEN", "CHILLED", "AMBIENT", name="locationtype")
item_type_enum = sa.Enum(
    "PURCHASED_FRESH",
    "PURCHASED_FROZEN",
    "PURCHASED_THEN_FROZEN",
    "HOMEMADE_FROZEN",
    "HOMEMADE_PRESERVED",
    name="itemtype",
)
t_users = sa.table(
    "users",
    sa.column("id", sa.Integer),
    sa.column("username", sa.String),
    sa.column("password_hash", sa.String),
    sa.column("email", sa.String),
    sa.column("role", sa.String),
    sa.column("is_active", sa.Boolean),
    sa.column("remember_token", sa.String),
    sa.column("created_at", sa.DateTime),
)
t_category = sa.table(
    "category",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("color", sa.String),
    sa.column("sort_order", sa.Integer),
    sa.column("created_at", sa.DateTime),
    sa.column("created_by", sa.Integer),
)
t_shelf_life = sa.table(
    "category_shelf_life",
    sa.column("category_id", sa.Integer),
    sa.column("storage_type", storage_type_enum),
    sa.column("months_min", sa.Integer),
    sa.column("months_max", sa.Integer),
)
t_location = sa.table(
    "location",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("location_type", location_type_enum),
    sa.column("is_active", sa.Boolean),
    sa.column("created_at", sa.DateTime),
    sa.column("created_by", sa.Integer),
)
t_settings = sa.table(
    "system_settings",
    sa.column("key", sa.String),
    sa.column("value", sa.String),
    sa.column("updated_at", sa.DateTime),
    sa.column("updated_by", sa.Integer),
)
t_item = sa.table(
    "item",
    sa.column("id", sa.Integer),
    sa.column("product_name", sa.String),
    sa.column("best_before_date", sa.Date),
    sa.column("freeze_date", sa.Date),
    sa.column("quantity", sa.Float),
    sa.column("unit", sa.String),
    sa.column("item_type", item_type_enum),
    sa.column("location_id", sa.Integer),
    sa.column("category_id", sa.Integer),
    sa.column("is_consumed", sa.Boolean),
    sa.column("created_at", sa.DateTime),
    sa.column("created_by", sa.Integer),
)
t_withdrawal = sa.table(
    "withdrawal",
    sa.column("item_id", sa.Integer),
    sa.column("quantity", sa.Float),
    sa.column("withdrawn_at", sa.DateTime),
    sa.column("withdrawn_by", sa.Integer),
)
t_login_attempt = sa.table(
    "login_attempt",
    sa.column("ip_address", sa.String),
    sa.column("fail_count", sa.Integer),
    sa.column("last_attempt", sa.DateTime),
)

ALL_TABLES = (
    "users",
    "category",
    "category_shelf_life",
    "location",
    "system_settings",
    "item",
    "withdrawal",
    "login_attempt",
)


def _insert_legacy_data(engine: sa.Engine) -> None:
    """Je eine Zeile pro Tabelle, so wie das Initialschema sie angelegt hätte."""
    with engine.begin() as conn:
        conn.execute(
            t_users.insert().values(
                id=1,
                username="admin",
                password_hash="hash",
                email="admin@test.local",
                role="admin",
                is_active=True,
                remember_token="altes-token",
                created_at=NOW,
            )
        )
        conn.execute(
            t_category.insert().values(id=1, name="Suppen", color="#4A7C59", sort_order=1, created_at=NOW, created_by=1)
        )
        conn.execute(t_shelf_life.insert().values(category_id=1, storage_type="FROZEN", months_min=2, months_max=3))
        conn.execute(
            t_location.insert().values(
                id=1, name="Truhe", location_type="FROZEN", is_active=True, created_at=NOW, created_by=1
            )
        )
        conn.execute(t_settings.insert().values(key="expiry_warning_days", value="7", updated_at=NOW, updated_by=1))
        conn.execute(
            t_item.insert().values(
                id=1,
                product_name="Kürbissuppe",
                best_before_date=date(2025, 12, 1),
                freeze_date=date(2025, 12, 1),
                quantity=1.5,
                unit="l",
                item_type="HOMEMADE_FROZEN",
                location_id=1,
                category_id=1,
                is_consumed=False,
                created_at=NOW,
                created_by=1,
            )
        )
        conn.execute(t_withdrawal.insert().values(item_id=1, quantity=0.5, withdrawn_at=NOW, withdrawn_by=1))
        conn.execute(t_login_attempt.insert().values(ip_address="203.0.113.9", fail_count=2, last_attempt=NOW))


def _row_counts(engine: sa.Engine) -> dict[str, int]:
    with engine.connect() as conn:
        return {table: conn.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one() for table in ALL_TABLES}


def test_upgrade_head_keeps_every_table_readable_and_data_intact(migration_db: tuple[AlembicConfig, sa.Engine]) -> None:
    """Initialschema + Bestandsdaten → upgrade head → ORM liest alle Tabellen, Daten erhalten."""
    cfg, engine = migration_db
    command.upgrade(cfg, INITIAL_REVISION)
    _insert_legacy_data(engine)

    command.upgrade(cfg, "head")

    assert _row_counts(engine) == dict.fromkeys(ALL_TABLES, 1)
    with Session(engine) as session:
        user = session.exec(select(User)).one()
        category = session.exec(select(Category)).one()
        shelf_life = session.exec(select(CategoryShelfLife)).one()
        location = session.exec(select(Location)).one()
        setting = session.exec(select(SystemSettings)).one()
        item = session.exec(select(Item)).one()
        withdrawal = session.exec(select(Withdrawal)).one()
        attempt = session.exec(select(LoginAttempt)).one()
    assert (user.username, user.session_version) == ("admin", 0)
    assert (category.name, category.parent_id) == ("Suppen", None)
    assert (shelf_life.storage_type, shelf_life.months_max) == (StorageType.FROZEN, 3)
    assert location.location_type == LocationType.FROZEN
    assert (setting.key, setting.value) == ("expiry_warning_days", "7")
    assert (item.item_type, item.quantity, item.freeze_date) == (ItemType.HOMEMADE_FROZEN, 1.5, date(2025, 12, 1))
    assert (withdrawal.quantity, withdrawal.withdrawn_by) == (0.5, 1)
    assert (attempt.ip_address, attempt.fail_count) == ("203.0.113.9", 2)


def test_downgrade_step_by_step_keeps_data_until_base(migration_db: tuple[AlembicConfig, sa.Engine]) -> None:
    cfg, engine = migration_db
    command.upgrade(cfg, INITIAL_REVISION)
    _insert_legacy_data(engine)
    command.upgrade(cfg, "head")

    command.downgrade(cfg, "-1")
    assert _row_counts(engine) == dict.fromkeys(ALL_TABLES, 1)
    command.downgrade(cfg, "-1")
    assert _row_counts(engine) == dict.fromkeys(ALL_TABLES, 1)

    command.downgrade(cfg, "base")
    assert sa.inspect(engine).get_table_names() in (["alembic_version"], [])


def test_models_and_migrations_describe_the_same_schema(migration_db: tuple[AlembicConfig, sa.Engine]) -> None:
    """Schema-Drift-Guard: ``alembic check`` findet nach ``upgrade head`` keine Differenz zu SQLModel.metadata."""
    cfg, engine = migration_db
    command.upgrade(cfg, "head")

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - nur im Fehlerfall
        pytest.fail(f"Modelle und Migrationen laufen auseinander:\n{exc}")


def test_no_migration_uses_sqlite_only_sql_or_lowercase_enum_values() -> None:
    """Fängt den bewusst eingebauten Fehler ``'frozen'`` statt ``FROZEN`` (und ``datetime('now')``) in jeder Migration."""
    offenders: list[str] = []
    for path in sorted(VERSIONS_DIR.glob("*.py")):
        source = path.read_text(encoding="utf-8")
        for needle in ("datetime('now')", "'frozen'", "'chilled'", "'ambient'", "'purchased_", "'homemade_"):
            if needle in source:
                offenders.append(f"{path.name}: {needle}")
    assert offenders == []
